<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Anyas-Seasons\**" />
    <Compile Remove="NumberParser\**" />
    <Compile Remove="TimesTable\**" />
    <EmbeddedResource Remove="Anyas-Seasons\**" />
    <EmbeddedResource Remove="NumberParser\**" />
    <EmbeddedResource Remove="TimesTable\**" />
    <None Remove="Anyas-Seasons\**" />
    <None Remove="NumberParser\**" />
    <None Remove="TimesTable\**" />
  </ItemGroup>

</Project>
